plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
}

group = 'dev.hytalemodding'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url = uri('https://maven.hytale.com/release') }
}

dependencies {
    compileOnly 'com.hypixel.hytale:Server:+'
    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.mysql:mysql-connector-j:8.4.0'
}

processResources {
    from('manifest.json') {
        into ''
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar') {
    enabled = false
}

tasks.named('shadowJar') {
    mergeServiceFiles()
    archiveClassifier.set('')
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}
