plugins {
    id 'java'
    id 'com.gradleup.shadow' version '9.3.1'
}

group = 'dev.hytalemodding'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
    maven { url = uri('https://maven.hytale.com/release') }
}

dependencies {
    compileOnly 'com.hypixel.hytale:Server:+'

    implementation 'com.google.code.gson:gson:2.11.0'
    implementation 'com.h2database:h2:2.2.224'
    implementation 'org.xerial:sqlite-jdbc:3.46.1.3'
    implementation 'com.mysql:mysql-connector-j:8.4.0'
    implementation 'org.mariadb.jdbc:mariadb-java-client:3.4.1'
    implementation 'org.postgresql:postgresql:42.7.4'
    implementation 'org.mongodb:mongodb-driver-sync:5.1.2'
}

processResources {
    from('manifest.json') {
        into ''
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

tasks.named('jar') {
    enabled = false
}

tasks.named('shadowJar') {
    mergeServiceFiles()
    archiveClassifier.set('')
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}
